version: '3.7'

services:
  timer-database:
    image: mysql:8.0.17
    container_name: timer-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  timer-back:
    build: .docker/timer-back
    container_name: timer-back
    depends_on:
      - timer-database
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
      - 8001:8001

  timer-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: timer-phpmyadmin
    environment:
      - PMA_HOST=timer-database
    ports:
      - 8080:80
    depends_on:
      - timer-database
