version: '3.7'

# Timer back
services:
  timer-database:
    image: mariadb:10
    container_name: timer-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  timer-back:
    build: .docker/timer-back
    container_name: timer-back
    depends_on:
      - timer-database
    volumes:
      - .:/var/www
      - /var/www/.env:/var/www/timer-back/.env:ro
    ports:
      - 80:80

  timer-back-node:
    image: node:12-alpine
    container_name: timer-back-node
    command: sh -c "yarn install && yarn encore dev --watch"
    volumes:
      - ./timer-back:/var/www/timer-back
    working_dir: /var/www/timer-back

#  timer-back-composer:
#    image: composer:1.9.0
#    container_name: timer-back-composer
#    command: install
#    depends_on:
#      - timer-back
#    working_dir: /var/www/timer-back

  timer-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: timer-phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 8000:80
    depends_on:
      - timer-database
# End timer back

# Timer ui
  timer-ui-node:
    image: node:12-alpine
    container_name: timer-ui-node
    command: sh -c "yarn install && yarn watch"
    volumes:
      - ./timer-ui:/var/www/timer-ui
    working_dir: /var/www/timer-ui
# End timer ui
