version: '3.7'
services:

  # Backend
  timer-database:
    image: 'mariadb:10'
    container_name: timer-database
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  timer-back:
    build: .docker/timer-back
    container_name: timer-back
    depends_on:
      - timer-database
    volumes:
      - './timer-back:/var/www/backend:cached'
      - './timer-back/logs:/var/log/backend'
    expose:
      - '9000'

  timer-web:
    build: .docker/timer-web
    container_name: timer-web
    restart: always
    depends_on:
      - timer-back
      - timer-database
    volumes:
      - './timer-back:/var/www/backend:cached'
#      - './logs:/var/log/nginx'
    ports:
       - '81:80'

  timer-back-node:
    image: 'node:12-alpine'
    container_name: timer-back-node
    command: sh -c "yarn install && yarn encore dev --watch"
    volumes:
      - './timer-back:/var/www/backend:cached'
    working_dir: /var/www/backend

  # timer-back-composer:
  #   image: 'composer:1.9'
  #   container_name: timer-back-composer
  #   command: install
  #   depends_on:
  #     - timer-back
  #   volumes:
  #     - './timer-back:/var/www/backend'

  timer-back-pma:
    image: phpmyadmin/phpmyadmin
    container_name: timer-back-pma
    environment:
      - PMA_HOST=timer-database
    ports:
      - '8000:8000'
    depends_on:
      - timer-database
  # Fin backend -------------------------

  # Timer ui
  timer-ui-node:
    image: 'node:12-alpine'
    container_name: timer-ui-node
    command: sh -c "yarn install && yarn watch"
    volumes:
      - './timer-ui:/var/www/ui:cached'
    working_dir: /var/www/ui
  # Fin timer ui --------------------------
